<a href="https://colab.research.google.com/github/Kodameratne/Data_Analysis-freecodecamp/blob/main/Exercises/NumPy/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.19.5


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
np.ones([2,2],dtype=np.int)

array([[1, 1],
       [1, 1]])

In [ ]:
np.ones([3,2],dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
X=np.arange(4,dtype=np.int)
np.ones_like(X)

array([1, 1, 1, 1])

In [ ]:
X=np.arange(4,dtype=np.int)
np.zeros_like(X)

array([0, 0, 0, 0])

In [ ]:
np.ones([4,4],dtype=np.int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
A=np.array([[2,3],[6,2]],dtype=float)
np.ones_like(A)*7

array([[7., 7.],
       [7., 7.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.randint(10,size=3)

array([7, 5, 4])

In [ ]:
np.random.randn(3,3,3)

array([[[ 1.17815806, -0.37880182,  1.20451614],
        [-0.18709403,  1.86797786, -0.29368525],
        [-2.20197499,  1.43349372,  0.21963361]],

       [[ 0.22309206,  1.19585263,  1.43503886],
        [ 0.91153294,  1.27776336,  0.12782225],
        [ 0.11016613,  0.57523502, -0.45253575]],

       [[-0.13830298, -0.27134382,  0.12719429],
        [ 0.27109983,  0.80959744,  0.80629404],
        [ 0.87693159,  1.13378274,  0.5989108 ]]])

In [ ]:
X=[1,2,3]
print(X,type(X))

Y=np.array(X)
print(Y,type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [ ]:
X=np.array([5,2,3], dtype=np.int)
print(X,id(X))

Y=np.copy(X)
print(Y,id(Y))

[5 2 3] 139976938845808
[5 2 3] 139976875558032


In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Z=np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))

800 bytes


In [ ]:
X = np.array(['A','B','C','D','E'])
X[0]

'A'

In [ ]:
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

In [ ]:
X = np.array(['A','B','C','D','E'])
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [ ]:
X = np.array(['A','B','C','D','E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0]

array([1, 2, 3, 4])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1]

array([13, 14, 15, 16])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0,0]

1

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1,-1]

16

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[:2,:2]

array([[1, 2],
       [5, 6]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[2:,2:]

array([[11, 12],
       [15, 16]])

In [ ]:
X = [-5, -3, 0, 10, 40]
np.array(X,np.float)

array([-5., -3.,  0., 10., 40.])

In [ ]:
X =np.array( [-5, -3, 0, 10, 40])
X[::-1]

array([40, 10,  0, -3, -5])

In [ ]:
X =np.array( [-5, -3, 0, 10, 40])
X.sort()
X

array([-5, -3,  0, 10, 40])

In [ ]:
X=np.zeros(10)
X[4]=1
X=X.astype(int)
X

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
X = np.array([10, 20, 30, 50])
X[3]=40
X

array([10, 20, 30, 40])

In [ ]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1]=np.array([1,1,1,1,])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [ ]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1,-1]=0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X+5


array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask=X<=0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask=X<=0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask=X>5
X[mask]

array([ 6, 10])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask=X>X.mean()
X[mask]

array([ 2,  5,  6, 10])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask=(X==2) |(X==10)
X[mask]

array([ 2, 10])

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X.all()

False

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X.any()

True

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X.sum()

9

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X.mean()

0.9

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.sum(axis=0)

array([28, 32, 36, 40])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [ ]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.max()

10